config/routes.rb
Rails.application.routes.draw do

  resources :cities
  resources :orders do
    member do
      get :search_orders
    end
  end

  root 'store#index'

  get "home" => 'pages#home'

  get "about" => 'pages#about'

  get "faqs" => 'pages#faqs'

  get "contact" => 'pages#contact'

  get "help" => 'pages#help'

  get "signup" => 'customers#new'

  get "login" => 'sessions#new'

  post "login" => 'sessions#create'

  delete "logout" => 'sessions#destroy'
  
  get "/store/:id" => 'store#show', as: :store_product

  get 'search_results' => 'store#search_results'

  resources :customers do
    member do
      get :remove_photo
    end
  end
  resources :products
  resources :categories
  resources :line_items
  resources :carts

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
      if current_item
        current_item.quantity += 1
      else
        current_item = line_items.build(product_id: product_id)
      end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessor :remember_token
  acts_as_paranoid
  before_save :downcase_email
  belongs_to :city
  has_many :orders

  validates :first_name, presence: true, length: {maximum: 200}
  validates :last_name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { in: 6..20 }, allow_nil: true
  validates :mobile, presence: true, length: {maximum: 10}
  validates :address, :date_of_birth, :pincode, :city_id, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def Customer.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Customer.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = Customer.new_token
    update_attribute(:remember_digest, Customer.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def downcase_email
    self.email = email.downcase
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  acts_as_paranoid
  has_many :line_items, dependent: :destroy
  belongs_to :customer


  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, :address, presence: true
  validates :payment_mode , inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :product_name, :brand, :description, :price, :quantity, :category_id, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 100 }
  validates :category_id, :numericality => { :greater_than_or_equal_to => 1 }
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      flash[:success] = 'Your cart is now empty'
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(customer)
    session[:customer_id] = customer.id
  end

  def remember(customer)
    customer.remember
    cookies.permanent.signed[:customer_id] = customer.id
    cookies.permanent[:remember_token] = customer.remember_token
  end

  def current_customer
    if (customer_id = session[:customer_id])
      @current_customer ||= Customer.find_by(id: customer_id)
    elsif (customer_id = cookies.signed[:customer_id])
      customer = Customer.find_by(id: customer_id)
      if customer && customer.authenticated?(cookies[:remember_token])
        log_in customer
        @current_customer = customer
      end
    end
  end

  def logged_in?
    !current_customer.nil?
  end

  def forget(customer)
    customer.forget
    cookies.delete(:customer_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_customer)
    session.delete(:customer_id)
    @current_customer = nil
  end

  def current_customer?(customer)
    customer == current_customer
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><div class="navbar-header">
        <a href="<%= root_path %>" class="navbar-brand"><span class="glyphicon glyphicon-shopping-cart"></span> Shop360</a>
        </div></li>
        <li><a href="<%= about_path %>">About</a></li>
        <li><a href="<%= faqs_path %>">FAQ's</a></li>
        <li><a href="<%= contact_path %>">Contact</a></li>
        <li><a href="<%= help_path %>">Help</a></li>
      </ul>
      
      <% if logged_in? and current_customer.admin? %>
        
        <ul class="nav navbar-nav navbar-right">
        <% display_name = current_customer.first_name + " " + current_customer.last_name%>
          <li><%= link_to "#{display_name}", current_customer, class: "active" %></li>
          <li><%= link_to "Admin's Cart", current_cart, class: "navbar-brand" %></li>
          <li><%= link_to "City", cities_path, class: "navbar-brand" %></li>
          <li><%= link_to "Customers", customers_path, class: "navbar-brand" %></li>
          <li><%= link_to "Products", products_path, class: "navbar-brand" %></li>
          <li><%= link_to "Category", categories_path, class: "navbar-brand" %></li>
          <li><%= link_to "Orders", orders_path, class: "navbar-brand" %></li>
          <li><%= link_to "Log out", logout_path, method: "delete", class: "navbar-brand" %></li>
        </ul>
      
      <% elsif logged_in? %>
       
        <ul class="nav navbar-nav navbar-right">
        <% display_name = current_customer.first_name + " " + current_customer.last_name%>
          <li><%= link_to "#{display_name}", current_customer, class: "active" %></li>
          <li><%= link_to "My Cart", current_cart, class: "navbar-brand" %></li>
          <li><%= link_to "My Order", search_orders_order_path(current_customer.id), class: "navbar-brand" %></li>
          <li><%= link_to "Log out", logout_path, method: "delete", class: "navbar-brand" %></li>
        </ul>
      
      <% else %>
      
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= signup_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>

      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_searchbar.html.erb
<%= form_tag(search_results_path, method: "get") do %>
  <%= label_tag :search_key, "Search Product:" %>
  <%= text_field_tag :search_key %>
  <%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop360</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navigation" %>
<%= render "layouts/searchbar" %>
<br>
<div class="container-fluid">
<div id="flash">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
<h1>About</h1>

</div>

app/views/pages/contact.html.erb
<div class="container">
<h1>Contact</h1>

</div>

app/views/pages/faqs.html.erb
<div class="container">
<h1>FAQ's</h1>

</div>

app/views/pages/help.html.erb
<div class="container">
<h1>Help</h1>
  
</div>

app/views/shared/_listProducts.html.erb
<% if @product.image? %>
  <p>
    <%= image_tag @product.image.url(:medium) %>
<% else %>
    <%= image_tag("missing.jpg", size: "300x300") %>
  </p>
<% end %>
<p>
  <strong>Product Name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price, :unit => "Rs ")%>
</p>

<% if @product.category %>
  <p>
      <strong>Category: </strong><%= @product.category.category_name %>
  </p>
<% end %>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>